### ISSUE TITLE
Consider adding a tab for issues assigned to you

### ISSUE THREAD

**Issue by jeanduplessis** [Mikescops/gitlab-notify-extension#2]
First, thank you for this extension!

I was wondering if you would consider adding a tab that can show the issues assigned to you.

Something similar to what you see at https://gitlab.com/dashboard/issues?assignee_username=### would be really great!

Happy to contribute some code for this if you consider it a feasible addition to the extension.

**Comment by Mikescops** [comment]
Hello,

I'm not sure to understand, by default the first tab shows the MRs that are assigned to you (assignee_username=your_username) and the second shows the MRs you created.

**Comment by Karimus** [comment]
As a freelance sysadmin, i have many gitlab access ans assigned issue. Not MR, i'd like to have a dedicated tab for issues and multi account feature
Once again, great job !

**Comment by Mikescops** [comment]
Right, I miss read the the title, it was "issues" not "MR", sorry.

I can do that, i'll take a look.

**Comment by Mikescops** [comment]
Concerning multi account, @Karimus do you mind opening a new separate issue?

**Comment by Karimus** [comment]
I can do that.
Milles mercis ;)

**Comment by Karimus** [comment]
Thanks a lot !
Going to use it right now.

Thank you

**Comment by Mikescops** [comment]
@Karimus you're welcome!

Update is available on Firefox and under review for Chrome :+1:

**Comment by jeanduplessis** [comment]
@Mikescops thank you very much for adding this feature 🙇
