### ISSUE TITLE
GitLab host address showing official gitlab.com server as placeholder makes user think it's the default

### ISSUE THREAD

**Issue by Porkepix** [Mikescops/gitlab-notify-extension#21]
There's a placeholder for GitLab host address that shows https://gitlab.com
As a user this made me think this greyed out entry was the default one and that if we were using it, we didn't need to fill out any value.
Failure proved me wrong. I think this should be more obvious to the users if they need to fill out a value in case they use gitlab.com, or actually have it as a default value if the input is empty.

**Comment by Mikescops** [comment]
Hello,

Thanks for the feedback, it's a good idea, I'll improve it.

**Comment by Mikescops** [comment]
Hello this is fixed in commit 2a71d205b195eee9625b1ef6946007e15d7c8355.

I decided not to put a default value but to clean the UI so it is easier to understand what is required.
