### ISSUE TITLE
Customize badge text

### ISSUE THREAD

**Issue by 0xjac** [Mikescops/gitlab-notify-extension#26]
The badge currently shows the number of assigned MRs.

It would be great if there was an option to choose which text is displayed on the badge (among the assigned MRs, created MRs, assigned issues, TODO items), or even better a way to select multiple ones and display them as the badge text with a separator like: <code>&sdot;</code> (`&sdot;`).

For example, for my workflow I'd love to see assigned MRs and TODO items. If I have 2 MRs assigned and 7 TODOs, I'd expect it would look something like: <code>2 &sdot; 7</code>.

**Comment by Mikescops** [comment]
Thanks for this idea, it was on my todo list. I'll work on it in the next updates for sure :+1:
