### ISSUE TITLE
Negative percentage in progress bar tooltip

### ISSUE THREAD

**Issue by fellowseb** [Mikescops/gitlab-notify-extension#28]
Hey !

I've noticed negative percentages when hovering over the progress bar in the To-Do List tab. I have 20 tasks to complete but "-12%" is displayed. Also I'm not quite sure what this progress is supposed to show :thinking: .

![gitlab_notify_bug](https://user-images.githubusercontent.com/34517235/100907405-9606d380-34ca-11eb-8205-5f0986214d53.png)

Thanks!

**Comment by Mikescops** [comment]
Good catch, it should represent how much PRs you reviewed.
