### ISSUE TITLE
Show PR in "To Review" tab when assigned as a reviewer 

### ISSUE THREAD

**Issue by rtouze** [Mikescops/gitlab-notify-extension#42]
PR form in Gitlab now has a `Reviewers` that works like `Assignees` field just above:

![image](https://user-images.githubusercontent.com/917039/106732356-e6a4c500-6610-11eb-828f-a3fa6fa7350b.png)

However, when I'm added in this Reviewers field, I won't see the PR in my "To Review" tab. It would be nice if both fields `Assignees` and `Reviewers` make the PR appear in the "To Review" tab.

**Comment by Mikescops** [comment]
Hello,

Thanks for the report, that's interesting. It works well for the "Under Review" but not for the "To Review".
I'll take a look.

**Comment by rtouze** [comment]
Yes, you're right, PR show up in "Under Review". I had a doubt, it seemed to me it was not the case when I spotted the issue. 
BTW, thanks for this extension, it's a great time saver.

**Comment by Mikescops** [comment]
I have opened an issue on GitLab side, the fix is too crappy for now.

https://gitlab.com/gitlab-org/gitlab/-/issues/301016

**Comment by Mikescops** [comment]
I'm sorry but the issue is still being reviewed on GitLab side

**Comment by Mikescops** [comment]
This has been fixed in v1.4.3, will publish to store soon.

**Comment by rtouze** [comment]
OK, thanks!
