### ISSUE TITLE
Under review MRs are shown as approved and rdy to be merge (but they aren't 🤦🏼)

### ISSUE THREAD

**Issue by mathieucollet** [Mikescops/gitlab-notify-extension#47]
I don't know if this is a real problem or if it's expected, but the extension tells me that all merge requests (in the "under review" tab) are approved and ready to be merged, even if they are not.

![image](https://user-images.githubusercontent.com/27346517/120555366-41053500-c3fb-11eb-9c19-a2d205d0ea4d.png)

![image](https://user-images.githubusercontent.com/27346517/120555459-67c36b80-c3fb-11eb-9ad9-42c5e26271ee.png)

**Comment by Mikescops** [comment]
Hello,

Thanks for the report, I've seen the same thing lately.

I think that the green check mark refers to the fact that the branch is merge-able (there is no conflict) but it's not taking in account pipelines nor unresolved threads.

It's clearly misleading so let's make it more accurate or adapt the wording.
