### ISSUE TITLE
MRs from Archived Projects are included in lists

### ISSUE THREAD

**Issue by tcoffin** [Mikescops/gitlab-notify-extension#72]
I have two open MRs on a project. That project was then Archived while the MRs were still open.
Those MRs continue to appear in the To Review and Under Review lists for the Extension. The list of personal MRs within the Gitlab interface does not show the MRs from the archived project.

Browser: Firefox
Extension Version: 1.5.1

Reproduction steps:
- Start with a project in the regular state
- Open an MR for that project
- Archive the project

**Comment by Mikescops** [comment]
As of today, it seems that the GitLab API does not provide a way to filter archived MRs. 
https://docs.gitlab.com/ee/api/merge_requests.html#list-group-merge-requests

Better close MRs in the archived project then... sadly

**Comment by bastienGranger** [comment]
@Mikescops As per the link you send above there is now a `non_archived` parameter to filter out MRs from archived projects it set to true.

**Comment by Mikescops** [comment]
Indeed as stated in the documentation : 

>  non_archived : Returns merge requests from non archived projects only. Default is true.

I'll close the issue but @tcoffin feel free to reopen if this is still an issue on your side, maybe there is something more.
