### ISSUE TITLE
Issue count appears on badge, but no issues listed in drop-down window.

### ISSUE THREAD

**Issue by drjmcauliffe** [Mikescops/gitlab-notify-extension#73]
![image](https://user-images.githubusercontent.com/1543976/178294039-c734f8df-18fb-4887-944a-9bbe1af7f423.png)

- Using Firefox 102.0. 
- Gave all rights to the Gitlab access token. 
- Self-hosted gitlab instance 15.0

![image](https://user-images.githubusercontent.com/1543976/178294562-83c5c035-d8b2-411b-b3c5-fecd5b60cf93.png)

I think this is a very cool extension but I would need to access the issues for it to be useful. Given that this hasn't been mentioned by anyone else, I'm sure I'm missing something basic with the setup.

Thanks for your help.

**Comment by Mikescops** [comment]
Thanks for reporting and sorry for the delay. It's fixed (issue in the code) and will be in the next release.
