### ISSUE TITLE
Extention does not seem to work? What should I do?

### ISSUE THREAD

**Issue by alexnb98** [Mikescops/gitlab-notify-extension#93]
Hey, thanks a lot for writing this extension, it is exactly what I've been missing all this time. I really would like to use it, but after adding my access code I get these errors. Is there anything I should do to get access. I created an access token with the `read_api`. 

<img width="612" alt="image" src="https://user-images.githubusercontent.com/35068342/213678525-6d6f09c4-a8e9-4ae2-bd1c-5839d8caa652.png">

<img width="715" alt="image" src="https://user-images.githubusercontent.com/35068342/213678556-4e7940bf-bee6-4270-b35e-aed64d062152.png">

I would really like to use it and would love to support you, if there is any way to donate. Thanks!

**Comment by Mikescops** [comment]
Hello @alexnb98 ,

As i see you're using a Chrome-like browser with the version 2.1.1 of the extension. I did a try on gitlab.com with my own account and could not reproduce the issue.

To debug this further I'll need more information:
- what browser are you using?
- what kind of network are you using? vpn? enterprise network?

That said I have an intuition, can you try to remove the `/` at the end of the host address? and use `https://gitlab.com`?
If that works, I'll make sure in the code that we handle nicely both case.

Concerning being a sponsor, it's much appreciated, so far I have applied to GitHub sponsor program but it's not approved yet!

**Comment by alexnb98** [comment]
Hello, @Mikescops. Thanks for the quick reply. I'm using chrome with the lasted update.

<img width="697" alt="image" src="https://user-images.githubusercontent.com/35068342/213917281-75ec6c87-699f-4dbc-9b32-7a02cac1b670.png">

I do use a VPN (CyberGhost) because I'm currently working from Malaysia. But, I have tried connecting to other servers. Also deactivating it and using my hotels wifi. Lastly also switching to my phone connection. In all cases, it does not work. I used a similar extension and there it worked right away, but I like your extension more. 

I also removed the `/` but unfortunately changed nothing. 

Is there anything else I should try?

**Comment by Mikescops** [comment]
Ok, so we'll have to debug this together.

For now what I recommend is to inspect what is happening on the console and on the network.

For this head to the Extension settings and click on "inspect views: service worker" : 

![image](https://user-images.githubusercontent.com/4266283/213944819-9dbc0984-2987-4277-8228-c88d597c7c7c.png)

Then a capture of both tabs network and console:
![image](https://user-images.githubusercontent.com/4266283/213944878-9e2b8260-7a70-4705-b78f-c14a5f996097.png)

Even better if you are okay you can share the full log file with me by exporting it by clicking on this button:

![image](https://user-images.githubusercontent.com/4266283/213944923-aaa83a0c-6843-46fd-ba4a-16ab159980b1.png)

**Comment by alexnb98** [comment]
Unfortunately, I cannot share the entire `.har` file with you, because actually most of the requests are successful and contain sensitive company information. 

But I can share some screenshots with you, hopefully, this helps. 

![image](https://user-images.githubusercontent.com/35068342/214092373-bd1b51ca-a7a7-4bf0-b305-fc5f86a21395.png)

<img width="1150" alt="image" src="https://user-images.githubusercontent.com/35068342/214093540-99f79400-2127-4327-ae38-a748b2841f0e.png">

<img width="1148" alt="image" src="https://user-images.githubusercontent.com/35068342/214093573-c21a36a8-bc5c-4364-93ba-20b0fbba2f2f.png">

It seems odd to me, that if one request failed, I see this error message in all tabs. 

<img width="720" alt="image" src="https://user-images.githubusercontent.com/35068342/214094585-e9ac7b81-9725-4516-90cb-db899e8848f1.png">

**Comment by alexnb98** [comment]
Hey, I solved the issue. The thing was that I don't use the "todo" feature. So, I had like 2k todos. Since, I saw that only that request was failing, I "marked all todos as done" and then the request succeeded! Nice, now I can use your amazing extension. Thanks for the fast help!

**Comment by Mikescops** [comment]
If I may I'll reopen the issue so I can keep track of two things:
- having a trailing slash in the domain cause a "fail to fetch" issue
- potentially a request could timeout, it shouldn't block the rest of the extension and be more explicit

**Comment by Nezteb** [comment]
Can confirm that having a trailing slash in the domain name causes the "Could not connect" error. Removing it fixes things. 👍
