### ISSUE TITLE
Unable to view the pop-up dialog

### ISSUE THREAD

**Issue by jfstgermain** [Mikescops/gitlab-notify-extension#94]
**Describe the bug**
The extension icon is displaying a badge with the number of "To review" items correctly.  When I click on the extension menu icon, the dialog appears for half a second and disappears.  I have encountered this behaviour in both Edge & Firefox browsers.

**Expected behavior**
I should be able to view the extension pop-up dialog

**Screenshots**
<img width="78" alt="image" src="https://user-images.githubusercontent.com/481217/220949529-dafb8946-d48d-408b-9ee6-8162e9660333.png">

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.2.1
 - Browser Edge 110.0.1587.50
 - Version110.0.1587.50

**Comment by Mikescops** [comment]
Can you do the following steps and let me know what kind of errors you see?

Right click on the icon, go to "Manage extension" :

<img width="441" alt="Screenshot 2023-02-23 at 18 42 49" src="https://user-images.githubusercontent.com/4266283/220987218-75e9a311-a221-46e6-91de-6330bce055d8.png">

Enable developer mode.

<img width="444" alt="Screenshot 2023-02-23 at 18 43 52" src="https://user-images.githubusercontent.com/4266283/220987686-2f713b43-09bb-4819-80ee-8ab3468526ce.png">

Click on inspect view:

<img width="444" alt="Screenshot 2023-02-23 at 18 47 31" src="https://user-images.githubusercontent.com/4266283/220988233-0520b96d-9863-416d-bbb8-432c16d833de.png">

It will open a console with logs and possibly some errors.

Something that could also help me is :
- do you have many todos?
- did the extension worked once or it break from the start?

**Comment by Mikescops** [comment]
No response from reporter, closing this. You can reopen if needed.
