### ISSUE TITLE
To Review tab + Notification Badge not updating

### ISSUE THREAD

**Issue by jdwile** [Mikescops/gitlab-notify-extension#99]
**Describe the bug**
The GItlab Notify "To Review" tab does not match what the site shows I have to review. I think it might have to do with new Gitlab layout/possible API changes. 

**Expected behavior**
I expect to see the correct merge requests show up in my To Review tab in the extension popup.

**Screenshots**
![image](https://github.com/Mikescops/gitlab-notify-extension/assets/57360196/5e04e6a5-959d-4b3f-a188-b73a77079a94)
![image](https://github.com/Mikescops/gitlab-notify-extension/assets/57360196/b0d8015f-4d32-4295-a565-65495e4a6ba9)
![image](https://github.com/Mikescops/gitlab-notify-extension/assets/57360196/059d9b18-677d-4ceb-a751-c400e762133f)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome 
 - Version 115.0.5790.171 (Official Build) (64-bit)

**Comment by Mikescops** [comment]
As I can't see the beginning, are they Work In Progress PRs or not?

**Comment by jdwile** [comment]
2 of them are Draft, and I have "View Draft MRs" checked in my settings 
![image](https://github.com/Mikescops/gitlab-notify-extension/assets/57360196/63b4dacd-bf7d-40a9-b1e0-84c8eb2fe876)

**Comment by JNaftali** [comment]
Have also been experiencing this problem for a while now. Some additional info in case it's helpful - pressing the "refresh" button doesn't cause things to update, but going into settings and clicking "test my settings" does

**Comment by Mikescops** [comment]
This should be fixed by #106, thanks for reporting!
